Add coop command
nomlab/swimmy pull request #134
Opened 2024-05-07 07:46 UTC by fujiwara-e

## 概要

coop コマンドの追加

# コマンドの概要

## 機能
岡山大学生協の営業中の店舗および営業時間を表示する．

## 使用方法
`swimmy coop open` もしくは `swimmy coop time`と入力する．

## 特徴
岡山大学生協webサイトをスクレイピングし，取得したデータを整理し表示する．

2024-05-09 04:45 UTC, fujiwara-e commented
## 変更点

- 改行数の削減
- CoopInfoFormatterのメソッドを変更
- 店舗が開いているかをcommand内で判定
- ファイル名をスネークケースに変更
 

コードレビューで頂いたアドバイスを基に，コードを修正しました

2024-05-10 07:14 UTC, yoshinari-nomura commented
- 無駄な改行が取れていないように思います
- 引数や関数名に統一的なルールを課してください．
- たとえば，get_shop_open(shopinfo) の引数が shpinfo というのは意味がよくわかりません．
- shopinfo と coopinfo の違いはなんでしょう
- get_shopinfo というメソッド名は ShopInfo を返すように思えるが実際には CoopInfo の **配列** を返しているの

2024-05-13 02:36 UTC, fujiwara-e commented
## 変更点

- 改行数の削減
- インデントを4から2へ変更
- CoopInfoFormatter -> ShopInfoFormatter 
- class CoopInfo -> class ShopInfo
- gemfile に nokogiri を追加
 
頂いたコメントを基に，コードを修正しました

2024-05-13 05:21 UTC, yoshinari-nomura reviewed
Review コメントしました．

2024-05-13 05:21 UTC, yoshinari-nomura commented on lib/swimmy/resource/coop_info.rb
> +      attr_accessor  :f_name,:state,:n_name,:time,:ex
f_name や state は，accessor に含めるべきではありません．
ex も使われている形跡がありません．何かのプレイスホルダーなら，_ で始めて，ふさわしい名前に変更したほうがいいです．また，必要に応じてコメントが必要だと思います．

2024-05-13 05:21 UTC, yoshinari-nomura commented on lib/swimmy/service/coop_service.rb
> +    class Coop
ここも，ファイル名とクラス名の対応が取れていません．

2024-05-13 05:21 UTC, yoshinari-nomura commented on lib/swimmy/service/coop_service.rb
> +        html.xpath('//h3[@class="bg-title-gray"]').each do |char|
何をしようとしているのか，どうしてこれで取り出せるのかコメントが必要だと思います．

なぜ char なのですか．1文字づつ処理している？

2024-05-13 05:21 UTC, yoshinari-nomura commented on lib/swimmy/service/coop_service.rb
> +          f_name.slice!(0)  #先頭の\nを削除
`#` の後に1つスペースを入れてください

2024-05-13 05:21 UTC, yoshinari-nomura commented on lib/swimmy/service/coop_service.rb
> +              d = 1
d とは，何で 4とは何でしょう．i もよく分かりません．
shopdata のような配列を使うのではなくて，それぞれが名前を識別できるような個別の変数を用意して，それを埋めていくような構造にしたほうがいいです．

2024-05-13 05:21 UTC, yoshinari-nomura commented on lib/swimmy/service/coop_service.rb
全体的に何をしようとしているのか理解し辛いです．
スクレイピングしようとしている HTML 全体がどういう構造になっているのかの概略や，
next_element を取り出す意味などをコメントで説明するといいです．

2024-05-13 05:21 UTC, yoshinari-nomura commented on lib/swimmy/service/coop_service.rb
> +              shops <<  Swimmy::Resource::ShopInfo.new(f_name,shopdata[0],shopdata[1],shopdata[2],shopdata[3])
コンマの後にはスペースを入れてください．

2024-05-13 05:21 UTC, yoshinari-nomura commented on lib/swimmy/resource/coop_info.rb
> +        @f_name, @state, @n_name ,@time ,@ex = f_name, state, n_name, time, ex
これは，オプショナルですが，
time は，相手の文字列をそのまま使うのではなくて，2つの時刻(数値)に置き換えて保存したほうがいいでしょう．start_time, end_time のような．
そのほうが，フォーマッタや比較が楽になります．

2024-05-13 05:21 UTC, yoshinari-nomura commented on lib/swimmy/resource/coop_info.rb
> +        if @state == "OPEN"
オプショナルですが，本来は，OPEN かどうかは，時刻から判断すべきで，open?(aTime = Time.now) のようなインタフェースになると思います．

2024-05-17 01:28 UTC, fujiwara-e commented
## 変更点

- フォーマッタを to_s メソッドに変更
- case 文内での重複を改善
- initialize する際に chomp を行うように変更
- class ShopInfo -> class CoopShop 
- accessor の削除，_ex は使用しないためスクレイピングで取得しないように変更
- service のファイル名を coop.rb に変更
- スクレイピングでのノードの探索方法を変更
-  time は start_time と end_time に分けてそれぞれ Time オブジェクトとして保存するように変更
- open? を現在時刻から判定するように変更
 
いただいたコメントを基に，コードを修正しました

2024-05-21 01:05 UTC, yoshinari-nomura requested changes
いいと思います．修正したら merge してもらってください．

2024-05-21 01:05 UTC, yoshinari-nomura commented on lib/swimmy/service/coop.rb
> +          f_name.slice!(0)  # 先頭の\nを削除
空白を取り除くには，strip や lstrip のほうが直感的だと思います

2024-05-21 01:58 UTC, fujiwara-e commented on lib/swimmy/service/coop.rb
> +          shops = shops + get_shopinfo(f_name, state, n_name, time)
get_shopinfo() では配列が返ってくるため += にしたいと思います．

2024-05-22 01:10 UTC, merged